modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This specifies Forge version 47.4.0 or newer
license="MIT" # Replace with your actual license
#issueTrackerURL="https://github.com/SpanoPrime/tales-of-folklore/issues" #optional

[[mods]] #mandatory
modId="talesoffolklore" #mandatory
version="0.1" #mandatory
displayName="Tales of Folklore" #mandatory
description="""In the Tales of Folklore, reality and legend blur together among misty hills and haunted forests.
Crafted to immerse players in a world inspired by cryptozoology, it invites you to embark on thrilling adventures through beautifully detailed biomes teeming with unique flora and fauna.

At the heart of the mod lies your hunt for four elusive cryptids—creatures once thought to exist only in myth… until now.

Brave the dense shadows of the Appalachian Forest or the icy expanse of the Forest of Spirits, where danger lurks behind every tree.
Track down the mighty Bigfoot, the cunning Snarly Yow, the ghostly Wendigo, and the malevolent Skinwalker—before they find you.

Will you uncover the truth behind the tales… or become just another legend lost to the woods?"""
authors="SpanoPrime, ReaperOfEvil" #optional
#logoFile="examplemod.png" #optional - Include if you want a logo for your mod

[[dependencies.talesoffolklore]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[47.4.0,)" #mandatory - Requires Forge 47.4.0 or newer
ordering="NONE"
side="BOTH"

[[dependencies.talesoffolklore]]
modId="minecraft" #mandatory
mandatory=true #mandatory
versionRange="[1.20.1,1.21)" #mandatory - Supports Minecraft 1.20.1 up to (but not including) 1.21
ordering="NONE"
side="BOTH"

# Optional metadata for additional functionality
#displayURL="https://github.com/SpanoPrime/tales-of-folklore" #optional homepage URL
#updateJSONURL="https://example.com/talesoffolklore-updates.json" #optional updates URL
#credits="Created by SpanoPrime and ReaperOfEvil. Built with MDK." #optional